package-lock.json
src/components/common/Coin/Coin.module.css
src/components/common/Coin/Coin.tsx
src/components/common/Swap/components/CurrencyBox/CurrencyBox.module.css
src/components/common/Swap/components/CurrencyBox/CurrencyBox.tsx

choose coin ui

---

src/components/common/ActionButton/ActionButton.module.css
src/components/common/ActionButton/ActionButton.tsx
src/components/common/ConfirmPopup/ConfirmPopup.module.css
src/components/common/ConfirmPopup/ConfirmPopup.tsx
src/components/common/StatusModal/index.module.css
src/components/common/StatusModal/index.tsx
src/components/common/Swap/components/SwapFailureModal/SwapFailureModal.module.css
src/components/common/Swap/components/SwapFailureModal/SwapFailureModal.tsx
src/components/common/Swap/components/SwapSuccessModal/SwapSuccessModal.module.css
src/components/common/Swap/components/SwapSuccessModal/SwapSuccessModal.tsx
src/components/common/TransactionFailureModal/TransactionFailureModal.module.css
src/components/common/TransactionFailureModal/TransactionFailureModal.tsx
src/components/pages/add-liquidity-page/components/AddLiquiditySuccessModal/AddLiquiditySuccessModal.module.css
src/components/pages/add-liquidity-page/components/AddLiquiditySuccessModal/AddLiquiditySuccessModal.tsx
src/components/pages/create-pool-page/components/CreatePoolSuccessModal/CreatePoolSuccessModal.tsx
src/components/pages/liquidity-page/components/Pools/DesktopPools/DesktopPools.module.css
src/components/pages/liquidity-page/components/Pools/DesktopPools/DesktopPools.tsx
src/components/pages/view-position-page/components/RemoveLiquiditySuccessModal/RemoveLiquiditySuccessModal.module.css
src/components/pages/view-position-page/components/RemoveLiquiditySuccessModal/RemoveLiquiditySuccessModal.tsx

- Button loader animation
- Using fullWidth for ActionButton in appropriate places
- Updating animation speed

Button styling

---

src/components/common/Footer/Footer.module.css
src/components/common/Footer/Footer.tsx

Footer Update:
- removed github, discord, x links and lable
- Adjusted desktop view alignment

Pixel perfect

---

public/css/globals.css
src/components/common/Header/Header.module.css
src/components/common/Swap/Swap.module.css
src/components/common/Swap/Swap.tsx
src/components/common/Swap/components/CurrencyBox/CurrencyBox.module.css
src/components/common/TransactionsHistory/TransactionsHistory.module.css
src/components/common/TransactionsHistory/TransactionsHistory.tsx

Promotion Bar
Transaction history component
CurrencyBox component

UI updates

---

src/components/common/Pagination/Pagination.module.css
src/components/icons/ArrowLeft/ArrowLeftIcon.tsx
src/components/icons/ArrowRight/ArrowRightIcon.tsx

Will update the svg's to have colors passed as props in the next pr

Pagination styling update

---

src/components/common/StatusModal/index.tsx
src/components/pages/add-liquidity-page/components/AddLiquidity/PreviewAddLiquidityDialog.tsx
src/components/pages/liquidity-page/components/Pools/DesktopPools/DesktopPoolRow.tsx
src/components/pages/liquidity-page/components/Pools/MobilePools/MobilePoolItem/MobilePoolItem.tsx
src/components/pages/view-position-page/components/PositionView/DesktopPositionView/DesktopPositionView.tsx
src/components/pages/view-position-page/components/PositionView/MobilePositionView/MobilePositionView.tsx

Fixes:
1) The 'L' in add liquidity and remove liquidity button needs to be small - 
https://pentagonstudio.neetorecord.com/watch/880ddb1b2470b13b8a4a

update Liquidity to liquidity for consistency with Figma

---

src/components/common/ActionButton/ActionButton.module.css
src/components/common/ActionButton/ActionButton.tsx
src/components/common/AprBadge/AprBadge.module.css
src/components/common/AprBadge/AprBadge.tsx
src/components/pages/add-liquidity-page/components/AddLiquidity/AddLiquidity.module.css
src/components/pages/add-liquidity-page/components/AddLiquidity/AddLiquidityDialog.tsx
src/components/pages/remove-liquidity-page/components/RemoveLiquidityContent/index.tsx

1. action button globally
2. APR badge 
3. Estimated APR in add liquidity and remove liquidity
4. fix apr value in add liquidity

Typography updates

---

src/components/common/Swap/Swap.tsx
src/components/common/Swap/components/ExchangeRate/ExchangeRate.module.css
src/components/common/Swap/components/ExchangeRate/ExchangeRate.tsx
src/components/pages/create-pool-page/components/CreatePool/CreatePoolDialog.tsx
src/components/pages/view-position-page/components/PositionView/ExchangeRate/ExchangeRate.tsx

- exchange conversion rate added on swap page
- fixed exchange rate typography

Added exchange conversion rate

---

src/components/pages/liquidity-page/LiquidityPageLayout.tsx

Please test before merging.
This will remove this:

Remove unwated back button

---

src/components/pages/liquidity-page/components/Pools/DesktopPools/DesktopPools.module.css
src/components/pages/liquidity-page/components/Pools/DesktopPools/DesktopPools.tsx
src/components/pages/liquidity-page/components/Positions/MobilePositions/DesktopPositions/DesktopPositions.module.css
src/components/pages/liquidity-page/components/Positions/MobilePositions/DesktopPositions/DesktopPositions.tsx
src/components/pages/points-page/PointsRankTable/PointsRankTable.module.css

- desktop pools and postions table head fix
- points page table fix

Points page table fix 

---

src/components/common/CurrencyBox/CurrencyBox.module.css
src/components/common/Swap/Swap.tsx
src/components/common/Swap/components/ExchangeRate/ExchangeRate.tsx

Closes https://github.com/athulp8457/mira-amm-web/issues/93

Fix: Extra Gap Between Swap Button and Currency Box

---

src/components/common/TransactionsHistory/TransactionsHistory.module.css
src/components/common/TransactionsHistory/TransactionsHistory.tsx

Closes https://github.com/athulp8457/mira-amm-web/issues/115

Added typography for transaction history component

---

src/components/pages/create-pool-page/components/CreatePool/CreatePool.tsx

Closes https://github.com/athulp8457/mira-amm-web/issues/112

fix: remove unwanted loadingOverlay

---

src/components/pages/add-liquidity-page/components/AddLiquidity/AddLiquidity.module.css
src/components/pages/create-pool-page/components/CreatePool/PreviewCreatePoolDialog.tsx

Closes https://github.com/athulp8457/mira-amm-web/issues/117
**Before**:
**After**:

Fix: Preview Create Pool Dialog UI and Typography

---

src/components/common/Swap/Swap.module.css
src/components/icons/Convert/ConvertIcon.tsx

Closes https://github.com/athulp8457/mira-amm-web/issues/122

Fix: Swap icon jumping

---

src/components/common/Header/Header.module.css

Closes https://github.com/athulp8457/mira-amm-web/issues/123

Fix: Promo banner icon small size on mobile

---

src/components/pages/liquidity-page/components/Pools/DesktopPools/DesktopPools.module.css
src/components/pages/liquidity-page/components/Pools/MobilePools/MobilePools.module.css
src/components/pages/liquidity-page/components/Positions/MobilePositions/DesktopPositions/DesktopPositions.module.css

Closes https://github.com/athulp8457/mira-amm-web/issues/96
@amaljosea 
TVL sort padding is a temporary solution and need to be handled in a better

UI Issues on Liquidity Page (Table Divider, Back Button, TVL Sort Padding) #96

---

src/components/common/AprBadge/AprBadge.module.css
src/components/pages/add-liquidity-page/components/AddLiquidity/AddLiquidity.module.css
src/components/pages/liquidity-page/LiquidityPageLayout.tsx
src/components/pages/liquidity-page/components/Boosts/BoostsBanner/BoostsBanner.module.css
src/components/pages/liquidity-page/components/Boosts/BoostsRewards/BoostsRewards.module.css
src/components/pages/liquidity-page/components/Positions/Positions.module.css
src/components/pages/view-position-page/components/PositionView/DesktopPositionView/DesktopPositionView.tsx
src/components/pages/view-position-page/components/PositionView/MiraBlock/MiraBlock.module.css
src/components/pages/view-position-page/components/PositionView/MobilePositionView/MobilePositionView.tsx

Part of https://github.com/athulp8457/mira-amm-web/issues/103 but not closes it

Temporary black bg color fallback

---

src/components/pages/view-position-page/components/PositionView/DesktopPositionView/DesktopPositionView.module.css
src/components/pages/view-position-page/components/PositionView/MiraBlock/MiraBlock.module.css
src/components/pages/view-position-page/components/PositionView/ReserveItem/ReserveItem.module.css

Closes https://github.com/athulp8457/mira-amm-web/issues/97
See [video](https://amal-jose.neetorecord.com/watch/1775d6c3d76ad04bd0c7) for Font Weights issue

Pixel Perfect Adjustments for Manage Positions Page

---

src/components/pages/remove-liquidity-page/components/Slider/index.module.css

Closes one point of https://github.com/athulp8457/mira-amm-web/issues/131

Remove Bg color

---

src/components/pages/add-liquidity-page/components/AddLiquidity/PreviewAddLiquidityDialog.tsx
src/components/pages/create-pool-page/components/CreatePool/PreviewCreatePoolDialog.tsx

Closes https://github.com/athulp8457/mira-amm-web/issues/124

boolean to toggle click feature used

---

src/components/pages/add-liquidity-page/components/AddLiquidity/AddLiquidityDialog.tsx
src/components/pages/remove-liquidity-page/components/RemoveLiquidityContent/index.tsx

Closes https://github.com/athulp8457/mira-amm-web/issues/127

Fix: APR badge broken

---

src/components/pages/view-position-page/components/PositionView/MobilePositionView/MobilePositionView.module.css
src/components/pages/view-position-page/components/PositionView/MobilePositionView/MobilePositionView.tsx

Fixed Typography in mobile position view
Before: 
After:

Fix: Typography mobile position view

---

src/components/pages/liquidity-page/LiquidityPageLayout.tsx
src/components/pages/view-position-page/components/PositionView/DesktopPositionView/DesktopPositionView.tsx
src/components/pages/view-position-page/components/PositionView/MobilePositionView/MobilePositionView.tsx

Fix: Promo block typo

---

src/components/common/CoinWithAmount/CoinWithAmount.tsx
src/components/pages/view-position-page/components/PositionView/DesktopPositionView/DesktopPositionView.tsx
src/components/pages/view-position-page/components/PositionView/MobilePositionView/MobilePositionView.tsx
src/utils/formatTokenAmount.ts

Closes https://github.com/athulp8457/mira-amm-web/issues/140
- Created formatTokenAmount 
- Replaced `formatDisplayAmount` function with `formatTokenAmount` in position view component

Fix: Token amount overflow in position manage

---

src/components/common/Swap/components/SettingsModalContent/SettingsModalContent.tsx
src/components/pages/add-liquidity-page/components/AddLiquidity/AddLiquidity.module.css
src/components/pages/add-liquidity-page/components/AddLiquidity/AddLiquidityDialog.tsx
src/components/pages/create-pool-page/components/CreatePool/CreatePoolDialog.tsx
src/components/pages/remove-liquidity-page/components/RemoveLiquidity/RemoveLiquidity.module.css

Closes [143](https://github.com/athulp8457/mira-amm-web/issues/143)

fix: liquidity fee tier toggle

---

src/components/pages/liquidity-page/components/Boosts/BoostsRewards/BoostsRewards.tsx

Localised loading ui, now displays the new loading animation while points and rank is being fetched

updated loading UI

---

src/components/common/StatusModal/index.module.css
src/components/common/StatusModal/index.tsx

Closes https://github.com/athulp8457/mira-amm-web/issues/145

fix: resolve content overflow issue in status modals

---

src/utils/constants.ts

fix: rename POINTS_BANNER_TITLE to correct value

---

libs/web/src/components/pages/liquidity-page/components/Pools/DesktopPools/DesktopPoolRow.tsx
libs/web/src/components/pages/liquidity-page/components/Pools/DesktopPools/DesktopPools.tsx
libs/web/src/components/pages/liquidity-page/components/Positions/MobilePositions/DesktopPositions/DesktopPosition.tsx

refactor: remove longer length prop from buttons on liquidity page

---

libs/web/src/components/pages/liquidity-page/components/Pools/MobilePools/MobilePools.module.css
libs/web/src/components/pages/liquidity-page/components/Pools/MobilePools/MobilePools.tsx
libs/web/src/components/pages/liquidity-page/components/Pools/Pools.module.css
libs/web/src/components/pages/liquidity-page/components/Pools/Pools.tsx

feat: Adjust Create Pool button layout next to sort box for small screens

---

libs/web/src/components/common/LoadingIndicator/LoadingIndicator.module.css

closes #167 
https://pentagonstudio.neetorecord.com/admin/recordings/7ca78580-8d21-4aff-bd67-1be5e0b6d199

Loading indicator speed fix

---

libs/web/src/components/common/CurrencyBox/CurrencyBox.tsx
libs/web/src/components/common/IconButton/IconButton.tsx
libs/web/src/components/common/SlippageSetting/SlippageSetting.tsx
libs/web/src/components/common/Swap/Swap.module.css
libs/web/src/components/common/Swap/Swap.tsx
libs/web/src/components/common/TextButton/TextButton.tsx

Screen blur fix when swap pending

---

libs/web/src/components/common/Header/Header.module.css
libs/web/src/components/common/Header/Header.tsx
libs/web/src/components/common/Swap/Swap.tsx

closes #180 
https://pentagonstudio.neetorecord.com/watch/8b1b34054f2260e580a0

Responsive navbar

---

libs/web/src/components/common/Swap/Swap.tsx
libs/web/src/components/common/Swap/components/ReviewSwap/ReviewSwap.tsx

closes #170 
https://pentagonstudio.neetorecord.com/admin/recordings/689b9440-c736-43f8-a28a-505c10a9eb87

fix: prevent flickering of rate, routing, and fee values on review screen

---

libs/web/src/components/common/Swap/components/SettingsModalContent/SettingsModalContent.module.css
libs/web/src/components/common/Swap/components/SettingsModalContent/SettingsModalContent.tsx

closes #169 
https://pentagonstudio.neetorecord.com/watch/0fe4e9c887579eca2334

Slippage settings fix

---

libs/web/src/components/pages/view-position-page/components/PositionView/MobilePositionView/MobilePositionView.module.css

Syle(manage-positions): improve action button height

---

libs/web/src/components/common/AprBadge/AprBadge.module.css

style(Aprbadge): refine APR badge dimensions and spacing

---

libs/web/src/components/common/Coin/Coin.tsx
libs/web/src/components/common/CoinPair/CoinPair.tsx
libs/web/src/components/common/CoinWithAmount/CoinWithAmount.tsx
libs/web/src/components/common/FallbackImage/FallbackImage.tsx
libs/web/src/components/common/Swap/components/CoinListItem/CoinListItem.tsx
libs/web/src/components/common/TransactionsHistory/TransactionsHistory.tsx

Image element was checking for existence of link, needed to also check if link was broken
Also, from my limited checking, images stored in a mira repo and not firebase were failing, wasnt just psycho coin's image
Closes https://github.com/athulp8457/mira-amm-web/issues/200

fix: image fallback fix

---

libs/web/src/components/common/ConnectButton/ConnectButton.module.css
libs/web/src/components/common/ConnectButton/ConnectButton.tsx
libs/web/src/components/common/Header/Header.module.css
libs/web/src/components/common/Header/Header.tsx
libs/web/src/components/common/Swap/Swap.module.css
libs/web/src/components/common/Swap/Swap.tsx

Widget fix

---

libs/web/src/components/common/SlippageSetting/SlippageSetting.module.css

style(slippage): improve spacing and layout for slippage settings label

---

apps/web/app/layout.tsx
libs/web/src/components/pages/add-liquidity-page/AddLiquidityPageLayout.tsx
libs/web/src/components/pages/landing-page/LandingPageLayout.tsx
libs/web/src/components/pages/liquidity-page/LiquidityPageLayout.tsx
libs/web/src/components/pages/points-page/PointsPageLayout.tsx
libs/web/src/components/pages/remove-liquidity-page/index.tsx
libs/web/src/components/pages/swap-page/SwapPageLayout.tsx

closes https://github.com/athulp8457/mira-amm-web/issues/203

fix: removed individual footer implementations -> global implementation
